on:
  workflow_dispatch:
  push:
    branches: main
  schedule:
    - cron: '30 1 * * *'
name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4.2'

      - name: Install R Dependencies
        uses: r-lib/actions/setup-renv@v2
        with:
          cache-version: 1

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          db_server: ${{ secrets.DB_SERVER }}
          db_uid: ${{ secrets.DB_UID }}
          db_pwd: ${{ secrets.DB_PWD }}
          nmcapi: ${{ secrets.NMCAPI }}
          db_url: ${{ secrets.DB_URL }}
          apikey: ${{ secrets.APIKEY }}
          servicekey: ${{ secrets.SERVICEKEY }}